# TCL File Generated by Component Editor 18.0
# Fri Aug 10 14:30:41 CDT 2018
# DO NOT MODIFY


# 
# ece453 "ece453" v1.0
# Joe Krachey 2018.08.10.14:30:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ece453
# 
set_module_property DESCRIPTION ""
set_module_property NAME ece453
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Joe Krachey"
set_module_property DISPLAY_NAME ece453
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ece453
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ece453.v VERILOG PATH ip/ece453/ece453.v TOP_LEVEL_FILE
add_fileset_file ece453.vh OTHER PATH ip/ece453/ece453.vh

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ece453
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ece453.v VERILOG PATH ip/ece453/ece453.v
add_fileset_file ece453.vh OTHER PATH ip/ece453/ece453.vh


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group de1_soc_ece453
set_module_assignment embeddedsw.dts.name ece453
set_module_assignment embeddedsw.dts.vendor uw_madison


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset clock_reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 slave_address address Input 5
add_interface_port avalon_slave_0 slave_byteenable byteenable Input 4
add_interface_port avalon_slave_0 slave_read read Input 1
add_interface_port avalon_slave_0 slave_readdata readdata Output 32
add_interface_port avalon_slave_0 slave_write write Input 1
add_interface_port avalon_slave_0 slave_writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock_sink
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset reset reset Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset clock_reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq_out irq Output 1


# 
# connection point gpio_in
# 
add_interface gpio_in conduit end
set_interface_property gpio_in associatedClock clock_sink
set_interface_property gpio_in associatedReset ""
set_interface_property gpio_in ENABLED true
set_interface_property gpio_in EXPORT_OF ""
set_interface_property gpio_in PORT_NAME_MAP ""
set_interface_property gpio_in CMSIS_SVD_VARIABLES ""
set_interface_property gpio_in SVD_ADDRESS_GROUP ""

add_interface_port gpio_in gpio_inputs export Input 32


# 
# connection point gpio_out
# 
add_interface gpio_out conduit end
set_interface_property gpio_out associatedClock clock_sink
set_interface_property gpio_out associatedReset ""
set_interface_property gpio_out ENABLED true
set_interface_property gpio_out EXPORT_OF ""
set_interface_property gpio_out PORT_NAME_MAP ""
set_interface_property gpio_out CMSIS_SVD_VARIABLES ""
set_interface_property gpio_out SVD_ADDRESS_GROUP ""

add_interface_port gpio_out gpio_outputs export Output 32

